[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-src 'self' https://www.google.com https://www.google.com/maps https://maps.google.com;"
